#! /bin/sh

#  █████████  ████████ █████████ ██ ██████████████
#  ██     ██  ██       ██     ██ ██ ██    ██    ██
#  ██     ██  ██       ██     ██ ██ ██ ██ ██ ██ ██
#  ██████████ ████████ █████████ ██ ██ ██ ██ ██ ██
#  ██      ██       ██ ██        ██ ██ ██ ██ ██ ██
#  ██      ██       ██ ██        ██    ██    ██ ██
#  ██████████ ████████ ██        ██████████████ ██

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 6
bspc config normal_border_color \#565f89
bspc config active_border_color \#7dcfff
bspc config focused_border_color \#7aa2f7

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

#### Window Rules #####
##  floating rules   ##
bspc rule -a Xarchiver state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Audacious state=floating
bspc rule -a qBittorrent state=floating
bspc rule -a firefox desktop='^1'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#### Auto start #######
setxkbmap fr &
dbus-update-activation-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY &
dwall -s tokyo
picom --config ~/.config/picom/picom.conf &
/usr/bin/polkit-dumb-agent &
~/.config/polybar/launch.sh &
xfce4-power-manager &
#clipit &
dunst &
mailspring --ignore-gpu-blocklist --enable-features=VaapiVideoDecoder --enable-gpu-rasterization --enable-zero-copy &
